import { NextRequest } from 'next/server'
import { createClient } from '@/lib/supabase/server'

export const dynamic = 'force-dynamic'

interface RouteContext {
  params: { id: string }
}

interface CropCoords {
  x: number
  y: number
  width: number
  height: number
}

interface EditAdjustments {
  exposure?: number | null
  shadows?: number | null
  highlights?: number | null
  contrast?: number | null
  saturation?: number | null
  temperature?: number | null
  sharpening?: number | null
}

function buildPsScript(
  title: string,
  crop: CropCoords,
  originalWidth: number,
  originalHeight: number,
  adj: EditAdjustments | null
): string {
  const left = Math.round(originalWidth * crop.x)
  const top = Math.round(originalHeight * crop.y)
  const right = Math.round(originalWidth * (crop.x + crop.width))
  const bottom = Math.round(originalHeight * (crop.y + crop.height))

  const lines: string[] = []

  lines.push(`// PhotoCurator — AI Crop & Edit Script`)
  lines.push(`// Photo: ${title}`)
  lines.push(`// Generated by PhotoCurator. Run via File > Scripts > Browse in Photoshop CS6+.`)
  lines.push(`//`)
  lines.push(`// This script uses saveAs (Save As dialog) so your original file is preserved.`)
  lines.push(`// The cropped version is saved as "cropped_<original filename>".`)
  lines.push(``)
  lines.push(`#target photoshop`)
  lines.push(``)
  lines.push(`var doc = app.activeDocument;`)
  lines.push(``)
  lines.push(`// --- CROP ---`)
  lines.push(`// AI-suggested crop: x=${crop.x.toFixed(4)}, y=${crop.y.toFixed(4)}, w=${crop.width.toFixed(4)}, h=${crop.height.toFixed(4)} (proportions)`)
  lines.push(`// Pixel bounds for ${originalWidth}x${originalHeight} original:`)
  lines.push(`var bounds = [${left}, ${top}, ${right}, ${bottom}];`)
  lines.push(`doc.crop(bounds);`)
  lines.push(``)

  if (adj) {
    const hasTone = Object.values(adj).some(v => v != null)
    if (hasTone) {
      lines.push(`// --- TONE ADJUSTMENTS ---`)

      if (adj.contrast != null || adj.exposure != null || adj.shadows != null || adj.highlights != null) {
        lines.push(`// Curves adjustment (exposure, shadows, highlights, contrast)`)
        lines.push(`var curvesLayer = doc.artLayers.add();`)
        lines.push(`curvesLayer.kind = LayerKind.CURVES;`)
        lines.push(`curvesLayer.name = "AI Tone";`)

        // Map exposure to midpoint shift on the curve
        if (adj.exposure != null) {
          // exposure in stops: +1 stop ≈ midpoint 128 -> 178 (roughly +50 per stop)
          const midShift = Math.round(adj.exposure * 50)
          const midOut = Math.min(255, Math.max(0, 128 + midShift))
          lines.push(`// Exposure: ${adj.exposure > 0 ? '+' : ''}${adj.exposure} stops`)
          lines.push(`var curveAdj = curvesLayer.adjustmentLayer;`)
          lines.push(`// Apply via curves dialog: midpoint ${midOut}/255`)
          lines.push(`app.doAction = false; // placeholder — set curve midpoint to ${midOut}`)
        }

        if (adj.contrast != null) {
          lines.push(``)
          lines.push(`// Contrast: ${adj.contrast > 0 ? '+' : ''}${adj.contrast}`)
          lines.push(`var bcLayer = doc.artLayers.add();`)
          lines.push(`bcLayer.kind = LayerKind.BRIGHTNESSCONTRAST;`)
          lines.push(`bcLayer.name = "AI Contrast";`)
          lines.push(`var bcAdj = bcLayer.adjustmentLayer;`)
          lines.push(`bcAdj.brightness = 0;`)
          lines.push(`bcAdj.contrast = ${adj.contrast};`)
        }
      }

      if (adj.saturation != null) {
        lines.push(``)
        lines.push(`// Saturation: ${adj.saturation > 0 ? '+' : ''}${adj.saturation}`)
        lines.push(`var hsLayer = doc.artLayers.add();`)
        lines.push(`hsLayer.kind = LayerKind.HUESATURATION;`)
        lines.push(`hsLayer.name = "AI Saturation";`)
        lines.push(`var hsAdj = hsLayer.adjustmentLayer;`)
        lines.push(`hsAdj.saturation = ${adj.saturation};`)
      }

      if (adj.temperature != null) {
        const warmth = adj.temperature > 0 ? 'warm' : 'cool'
        const density = Math.min(25, Math.abs(adj.temperature) / 4)
        lines.push(``)
        lines.push(`// Temperature: ${adj.temperature > 0 ? '+' : ''}${adj.temperature} (${warmth})`)
        lines.push(`var pfLayer = doc.artLayers.add();`)
        lines.push(`pfLayer.kind = LayerKind.PHOTOFILTER;`)
        lines.push(`pfLayer.name = "AI Temperature";`)
        lines.push(`var pfAdj = pfLayer.adjustmentLayer;`)
        lines.push(`pfAdj.color = ${adj.temperature > 0 ? 'new SolidColor() /* warm: 85, 60, 10 */' : 'new SolidColor() /* cool: 0, 100, 200 */'};`)
        lines.push(`pfAdj.density = ${density.toFixed(0)};`)
        lines.push(`pfAdj.luminosity = true;`)
      }

      if (adj.sharpening != null && adj.sharpening > 0) {
        // Unsharp Mask: amount 0-500%, radius 0.1-250px, threshold 0-255
        // Map sharpening 0-150 to amount 50-200%, radius stays at 1.0, threshold at 3
        const amount = Math.round(50 + (adj.sharpening / 150) * 150)
        lines.push(``)
        lines.push(`// Sharpening: ${adj.sharpening}/150`)
        lines.push(`doc.activeLayer.applyUnSharpMask(${amount}, 1.0, 3);`)
      }
    }
  }

  lines.push(``)
  lines.push(`// --- SAVE AS NEW FILE ---`)
  lines.push(`// SaveAs preserves your original. The cropped file is saved alongside it.`)
  lines.push(`var saveFile = new File(doc.path + "/cropped_" + doc.name);`)
  lines.push(`var saveOpts = new JPEGSaveOptions();`)
  lines.push(`saveOpts.quality = 12; // maximum`)
  lines.push(`doc.saveAs(saveFile, saveOpts, true, Extension.LOWERCASE);`)
  lines.push(``)
  lines.push(`alert("Done! Saved as cropped_" + doc.name);`)

  return lines.join('\n')
}

export async function GET(_req: NextRequest, { params }: RouteContext) {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: photo } = await supabase
    .from('photos')
    .select('*')
    .eq('id', params.id)
    .eq('user_id', user.id)
    .single()

  if (!photo) return Response.json({ error: 'Not found' }, { status: 404 })

  // These columns exist after migration 20240008000000_add_crop_preview_fields.sql.
  // Cast through unknown until Supabase types are regenerated with: npx supabase gen types typescript --local > lib/supabase/types.ts
  const p = photo as unknown as Record<string, unknown>
  const crop = ((p.user_crop_coords ?? p.ai_crop_coords) ?? null) as CropCoords | null
  if (!crop) {
    return Response.json({ error: 'No crop data available. Re-analyze the photo to generate crop coordinates.' }, { status: 422 })
  }

  const originalWidth = p.original_width as number | null
  const originalHeight = p.original_height as number | null
  if (!originalWidth || !originalHeight) {
    return Response.json({ error: 'Original dimensions not available. Re-analyze the photo to generate the script.' }, { status: 422 })
  }

  const adj = (p.ai_edit_adjustments ?? null) as EditAdjustments | null
  const title = (p.ai_title as string | null) ?? (p.filename as string | null) ?? 'photo'
  const script = buildPsScript(title, crop, originalWidth, originalHeight, adj)

  const safeTitle = title.replace(/[^a-z0-9]/gi, '-').toLowerCase().slice(0, 40)
  return new Response(script, {
    headers: {
      'Content-Type': 'application/javascript',
      'Content-Disposition': `attachment; filename="crop-${safeTitle}.jsx"`,
    },
  })
}
